name = "thaigov2569"
compatibility_date = "2024-02-27"
pages_build_output_dir = "dist"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "thaigov2569-db"
database_id = "af62e7d7-5a46-4ec8-b34d-72cb17993428"  # D1 database ID
